POST http://localhost:8082/api/auth/signup
Content-Type: application/json
//in case you want to sign up as office manager or admin, change role to that value

{
  "username": "test_user",
  "email": "test_user@mail.com",
  "password": "Test123456",
  "role": [
    "admin"
  ]
}

> {%
    client.test("Signup successful", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###Sign in request
POST http://localhost:8082/api/auth/signin
Content-Type: application/json

{
  "username": "test_admin",
  "password": "Test123456"
}


> {%
    client.test("User logged in successfully", function() {
       const setCookieValue = response.headers.valueOf("Set-Cookie");
       client.global.set("cookie_employee", setCookieValue);
       client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
GET {{travel}}/api/test/all

###
GET {{travel}}/api/test/employee
Cookie: {{cookie_employee}}

> {%
    client.test("Get employee successful", function() {
        client.assert(response.status === 200, "Response status is not 200")
    });
%}

###

GET {{travel}}/api/test/office-manager
Cookie: {{cookie_employee}}

> {%
    client.test("Get office manager successfully", function() {
         client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

GET {{travel}}/api/test/admin
Cookie: {{cookie_employee}}

> {%
    client.test("Get admin successful", function() {
         client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
POST http://localhost:8082/api/auth/signout
Content-Type: application/json

> {%
    client.test("Sign out successful", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
